id: P003012
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN5177
  title: ཕྱག་ཆེན་སྔོན་འགྲོའི་ངག་འདོན།
  author: ''
  volumes:
    c7bcfa6884a14a4baa64fc2c39b21cad:
      image_group_id: I3CN5179
      title: ''
      volume_number: 1
      total_pages: 124
      base_file: v001.txt
