id: IF330859F
legacy_id: P003012
ocr_import_info:
  bdrc_scan_id: W3CN5177
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T05:51:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:52:58.952068+00:00'
last_modified: 2022-09-03 22:53:05.392695
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5177
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5177
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་ཆེན་སྔོན་འགྲོའི་ངག་འདོན།
statistics:
  ocr_word_mean_confidence_index: 0.9358511705665394
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN5179:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5179
      total_pages: 124
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5179.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9358511705665394
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
